version: "3"

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    volumes:
      - mongodb_data:/data/db
    ports:
      - "27018:27017"

  media:
    build:
      context: ./media/
      dockerfile: Dockerfile
    container_name: media
    working_dir: /app
    ports:
      - "3000:3000"
    volumes:
      - ./media/:/app
    command: ["yarn", "dev"]

volumes:
  mongodb_data:
    driver: local
